import { default as Card } from './Card';
import { default as CardActions } from './CardActions';
import { default as CardHeader } from './CardHeader';
import { default as CardMedia } from './CardMedia';
import { default as CardSupportingVisual } from './CardSupportingVisual';
import { default as CardText } from './CardText';
import { default as CardTitle } from './CardTitle';
declare const _default: typeof Card & {
    Actions: typeof CardActions;
    Header: typeof CardHeader;
    Media: typeof CardMedia;
    SupportingVisual: typeof CardSupportingVisual;
    Text: typeof CardText;
    Title: typeof CardTitle;
};
export default _default;
export type { CardType } from './Card';
export type { CardActionsType } from './CardActions';
export type { CardHeaderType } from './CardHeader';
export type { CardMediaType } from './CardMedia';
export type { CardSupportingVisualType } from './CardSupportingVisual';
export type { CardTextType } from './CardText';
export type { CardTitleType } from './CardTitle';
